"""Shared pytest fixtures and lightweight fakes.

The fakes let us exercise the full controller/CLI pipeline without installing
faster-whisper, PySide6, sounddevice or a platform's native input stack.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from app.config import Paths, get_paths
from app.models import PlatformKind, Settings
from app.platform.base import PasteResult, PlatformAdapter, PlatformCapabilities
from app.services.asr_base import ASRBackend, TranscriptionResult, TranscriptionSegment

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture()
def data_dir(tmp_path, monkeypatch) -> Path:
    """Point all persisted state at a throwaway temp directory."""

    monkeypatch.setenv("TALKPASTE_DATA_DIR", str(tmp_path))
    return tmp_path


@pytest.fixture()
def paths(data_dir) -> Paths:
    return get_paths().ensure()


@pytest.fixture()
def settings() -> Settings:
    return Settings()


@pytest.fixture()
def sample_wav() -> Path:
    """Path to the bundled WAV fixture (generated by scripts/make_fixture.py)."""

    wav = FIXTURES / "short_en.wav"
    if not wav.exists():  # generate on demand so tests are self-contained
        import scripts.make_fixture as mk  # type: ignore

        mk.write_wav(wav, mk.synth(1.4))
    return wav


class FakeASRBackend(ASRBackend):
    """Deterministic ASR backend that returns a canned transcript."""

    name = "fake"

    def __init__(self, settings, transcript: str = "hello comma world period") -> None:
        super().__init__(settings)
        self._loaded = False
        self.transcript = transcript
        self.transcribe_calls = 0

    def load(self) -> None:
        self._loaded = True

    def is_loaded(self) -> bool:
        return self._loaded

    def transcribe(self, audio, sample_rate: int = 16000, language=None) -> TranscriptionResult:
        self.transcribe_calls += 1
        duration = float(len(audio)) / sample_rate if len(audio) else 0.0
        return TranscriptionResult(
            text=self.transcript,
            segments=[TranscriptionSegment(0.0, duration, self.transcript)],
            language="en",
            duration=duration,
            inference_seconds=0.01,
            backend=self.name,
            model="fake-model",
        )


class FakeAdapter(PlatformAdapter):
    """In-memory platform adapter for pipeline tests."""

    kind = PlatformKind.LINUX_X11

    def __init__(self, settings, *, can_inject: bool = True) -> None:
        super().__init__(settings)
        self.can_inject = can_inject
        self.clipboard: str | None = None
        self.inserted: list[str] = []
        self.started = False

    def detect_capabilities(self) -> PlatformCapabilities:
        return PlatformCapabilities(
            kind=self.kind,
            session_type="x11",
            hotkey_available=True,
            hotkey_method="fake",
            paste_available=self.can_inject,
            paste_method="fake" if self.can_inject else "copy-only",
            clipboard_available=True,
            clipboard_method="memory",
        )

    def start_hotkeys(self, callback) -> None:
        self.started = True
        self._callback = callback

    def stop_hotkeys(self) -> None:
        self.started = False

    def insert_text(self, text: str) -> PasteResult:
        self.set_clipboard(text)
        if self.can_inject:
            self.inserted.append(text)
            return PasteResult(copied=True, injected=True, method="fake-paste")
        return PasteResult(
            copied=True, injected=False, method="copy-only",
            needs_manual_paste=True,
        )

    def get_clipboard(self) -> str | None:
        return self.clipboard

    def set_clipboard(self, text: str) -> bool:
        self.clipboard = text
        return True


@pytest.fixture()
def fake_asr_cls():
    return FakeASRBackend


@pytest.fixture()
def fake_adapter(settings):
    return FakeAdapter(settings)


@pytest.fixture()
def silence():
    return np.zeros(16000, dtype=np.float32)
